#!/usr/bin/env python
"""
.. module:: lcad_to_ldraw
   :synopsis: Generates a ldraw format file from a lcad model.

.. moduleauthor:: Hazen Babcock
"""

import os
import sys

import lcad_language.interpreter as interpreter

if (len(sys.argv)!=3):
    print "usage: <lcad file> <ldraw file>"
    exit()

# Generate parts.
with open(sys.argv[1]) as fp:
    parts = interpreter.execute(fp.read()).getParts()

print "Model has", len(parts), "parts."

# Save.
with open(sys.argv[2], "w") as fp:
    fp.write("0 // Do not edit, automatically generated by openlcad from " + os.path.basename(sys.argv[1]) + "\n")
    for part in parts:
        fp.write(part.toLDraw() + "\n")

print "Done."
