# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'partviewer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.partsTreeView = PartTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partsTreeView.sizePolicy().hasHeightForWidth())
        self.partsTreeView.setSizePolicy(sizePolicy)
        self.partsTreeView.setObjectName("partsTreeView")
        self.verticalLayout_2.addWidget(self.partsTreeView)
        self.filterGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.filterGroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.filterGroupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.filterGroupBox.setObjectName("filterGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filterGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterLineEdit = QtWidgets.QLineEdit(self.filterGroupBox)
        self.filterLineEdit.setObjectName("filterLineEdit")
        self.verticalLayout.addWidget(self.filterLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.clearPushButton = QtWidgets.QPushButton(self.filterGroupBox)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout_2.addWidget(self.clearPushButton)
        self.filterPushButton = QtWidgets.QPushButton(self.filterGroupBox)
        self.filterPushButton.setObjectName("filterPushButton")
        self.horizontalLayout_2.addWidget(self.filterPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.filterGroupBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rebrickableGroupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.rebrickableGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.rebrickableGroupBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.rebrickableGroupBox.setObjectName("rebrickableGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rebrickableGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rebrickCheckBox = QtWidgets.QCheckBox(self.rebrickableGroupBox)
        self.rebrickCheckBox.setObjectName("rebrickCheckBox")
        self.horizontalLayout.addWidget(self.rebrickCheckBox)
        self.apiLabel = QtWidgets.QLabel(self.rebrickableGroupBox)
        self.apiLabel.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.apiLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.apiLabel.setObjectName("apiLabel")
        self.horizontalLayout.addWidget(self.apiLabel)
        self.apiLineEdit = QtWidgets.QLineEdit(self.rebrickableGroupBox)
        self.apiLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.apiLineEdit.setObjectName("apiLineEdit")
        self.horizontalLayout.addWidget(self.apiLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.rebrickableGroupBox)
        self.partInfoGroupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.partInfoGroupBox.setObjectName("partInfoGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.partInfoGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.partInfoLabel = QtWidgets.QLabel(self.partInfoGroupBox)
        self.partInfoLabel.setObjectName("partInfoLabel")
        self.verticalLayout_5.addWidget(self.partInfoLabel)
        self.widget = QtWidgets.QWidget(self.partInfoGroupBox)
        self.widget.setMinimumSize(QtCore.QSize(204, 204))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.partImageFrame = QtWidgets.QFrame(self.widget)
        self.partImageFrame.setMinimumSize(QtCore.QSize(202, 202))
        self.partImageFrame.setMaximumSize(QtCore.QSize(202, 202))
        self.partImageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.partImageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.partImageFrame.setObjectName("partImageFrame")
        self.horizontalLayout_3.addWidget(self.partImageFrame)
        spacerItem2 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.partInfoGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.colorListView = ColorListView(self.groupBox)
        self.colorListView.setObjectName("colorListView")
        self.gridLayout_2.addWidget(self.colorListView, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Part Viewer"))
        self.filterGroupBox.setTitle(_translate("MainWindow", "Filter"))
        self.clearPushButton.setText(_translate("MainWindow", "Clear"))
        self.filterPushButton.setText(_translate("MainWindow", "Filter"))
        self.rebrickableGroupBox.setTitle(_translate("MainWindow", "Rebrickable"))
        self.rebrickCheckBox.setText(_translate("MainWindow", "query rebrickable"))
        self.apiLabel.setText(_translate("MainWindow", "API key"))
        self.partInfoGroupBox.setTitle(_translate("MainWindow", "Part Information"))
        self.partInfoLabel.setText(_translate("MainWindow", "No part selected"))
        self.groupBox.setTitle(_translate("MainWindow", "Colors"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from colorListView import ColorListView
from partTreeView import PartTreeView
